- hosts: localhost
  roles:
    - role: geerlingguy.java
      become: yes
  become: true
  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - htop
      - mc
      - tmux
